<?php
/**
 * @var $this Bubble_RequireLogin_Block_Adminhtml_System_Config_Fieldset_Hint
 */
?>
<div class="box">
    <div style="background:url('//i.imgur.com/NtYmWIh.png') no-repeat left center;padding-left:55px;min-height:42px;">
        <a href="https://github.com/jreinke/magento-require-login" target="_blank" style="float:right;">
            <img src="//i.imgur.com/QVKwCFx.png" alt="Fork me on GitHub" title="Fork me on GitHub" />
        </a>
        <h4><?php echo $this->helper('bubble_requirelogin')->__('Bubble RequireLogin is a module that can force user authentication in frontend.'); ?></h4>
        <p style="margin-bottom:0;"><?php echo $this->helper('bubble_requirelogin')->__('Full overview available'); ?> <a href="<?php echo $this->escapeHtml($this->helper('bubble_requirelogin')->__('http://www.bubblecode.net/en/2012/05/15/a-magento-module-to-require-login-on-your-store/')); ?>" target="_blank"><?php echo $this->helper('bubble_requirelogin')->__('here'); ?></a>.</p>
    </div>
</div>